export enum VehicleCategory {
  HYPERCAR = 'hypercar',
  SUPERCAR = 'supercar',
  SPORTS = 'sports',
  JDM = 'JDM',
  MUSCLE = 'muscle',
  CLASSIC = 'classic',
  LUXURY = 'luxury',
  SUV = 'SUV',
  SEDAN = 'sedan',
  PICKUP = 'pickup',
  OFF_ROAD = 'off-road',
  COMPACT = 'compact',
  CONVERTIBLE = 'convertible',
  WAGON = 'wagon',
  ELECTRIC = 'electric',
  VAN = 'van',
  CONCEPT = 'concept',
}
